export const cuisineFlags: Record<string, string> = {
    italian: "🇮🇹",
    french: "🇫🇷",
    spanish: "🇪🇸",
    dutch: "🇳🇱",
    polish: "🇵🇱",
    thai: "🇹🇭",
    japanese: "🇯🇵",
    indian: "🇮🇳",
    chinese: "🇨🇳",
    korean: "🇰🇷",
    american: "🇺🇸",
    mexican: "🇲🇽",
    brazilian: "🇧🇷",
};